{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "import requests  \n",
    "import datetime\n",
    "\n",
    "class BotAlice:\n",
    "    \n",
    "    greet_bot = BotAlice(token)  \n",
    "    greetings = ('hello', 'hi', 'greetings', 'sup')  \n",
    "    now = datetime.datetime.now()\n",
    "\n",
    "    def __init__(self, token):\n",
    "        self.token = '1158827389:AAEpk04wQa3_9YTzzqd20tDNOBImH0ctngo'\n",
    "        self.api_url = \"https://api.telegram.org/bot{}/\".format(token)\n",
    "\n",
    "    def get_updates(self, timeout=30):\n",
    "        method = 'getUpdates'\n",
    "        params = {'timeout': timeout}\n",
    "        resp = requests.get(self.api_url + method, params)\n",
    "        result_json = resp.json()['result']\n",
    "        return result_json\n",
    "\n",
    "    def send_message(self, chat_id, text):\n",
    "        params = {'chat_id': chat_id, 'text': text}\n",
    "        method = 'sendMessage'\n",
    "        resp = requests.post(self.api_url + method, params)\n",
    "        return resp\n",
    "\n",
    "    def get_last_update(self):\n",
    "        get_result = self.get_updates()\n",
    "\n",
    "        if len(get_result) > 0:\n",
    "            last_update = get_result[-1]\n",
    "        else:\n",
    "            last_update = get_result[len(get_result)]\n",
    "\n",
    "        return last_update\n",
    "\n",
    "    def main():  \n",
    "        new_offset = None\n",
    "        today = now.day\n",
    "        hour = now.hour\n",
    "\n",
    "        while True:\n",
    "            greet_bot.get_updates(new_offset)\n",
    "\n",
    "            last_update = greet_bot.get_last_update()\n",
    "\n",
    "            last_update_id = last_update['update_id']\n",
    "            last_chat_text = last_update['message']['text']\n",
    "            last_chat_id = last_update['message']['chat']['id']\n",
    "            last_chat_name = last_update['message']['chat']['first_name']\n",
    "\n",
    "            if last_chat_text.lower() in greetings and today == now.day and 6 <= hour < 12:\n",
    "                greet_bot.send_message(last_chat_id, 'Good Morning  {}'.format(last_chat_name))\n",
    "                today += 1\n",
    "\n",
    "            elif last_chat_text.lower() in greetings and today == now.day and 12 <= hour < 17:\n",
    "                greet_bot.send_message(last_chat_id, 'Good Afternoon {}'.format(last_chat_name))\n",
    "                today += 1\n",
    "\n",
    "            elif last_chat_text.lower() in greetings and today == now.day and 17 <= hour < 23:\n",
    "                greet_bot.send_message(last_chat_id, 'Good Evening  {}'.format(last_chat_name))\n",
    "                today += 1\n",
    "\n",
    "            new_offset = last_update_id + 1\n",
    "\n",
    "    if __name__ == '__main__':  \n",
    "        try:\n",
    "            main()\n",
    "        except KeyboardInterrupt:\n",
    "            exit()"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.6"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
